services:
  serverless:
    build:
      context: .
      args:
        SERVERLESS_ORG: ${SERVERLESS_ORG}
        SERVERLESS_TOKEN: ${SERVERLESS_TOKEN}
    env_file:
      - .env
    environment:
      - AWS_ACCESS_KEY_ID=${ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY}
      - BUCKET_NAME=${BUCKET_NAME}
      - SERVERLESS_ORG=${SERVERLESS_ORG}
      - SERVERLESS_TOKEN=${SERVERLESS_TOKEN}
    volumes:
      - .:/usr/src/app
    entrypoint: ["serverless", "deploy"]
    command: serverless deploy